/**
 * Auto-generated Hindi chapter titles for MentorsDaily Foundation Plan.
 * Keys: English chapter name, and moduleId|chapterNumber.
 */
export const CHAPTER_NAME_HI_BY_EN = {
  "Historical Background": "ऐतिहासिक पृष्ठभूमि",
  "Making of the Constitution": "संविधान का निर्माण",
  "Salient Features of the Constitution": "संविधान की मुख्य विशेषताएँ",
  "Preamble of the Constitution": "संविधान की प्रस्तावना",
  "Union and its Territory": "संघ और उसका राज्यक्षेत्र",
  "Citizenship": "नागरिकता",
  "Fundamental Rights": "मौलिक अधिकार",
  "Directive Principles of State Policy": "राज्य के नीति निदेशक तत्व",
  "Fundamental Duties": "मौलिक कर्तव्य",
  "Amendment of the Constitution": "संविधान का संशोधन",
  "Basic Structure of the Constitution": "संविधान की मूल संरचना",
  "Parliamentary System": "संसदीय प्रणाली",
  "Federal System": "संघीय प्रणाली",
  "Centre–State Relations": "केंद्र-राज्य संबंध",
  "Inter-State Relations": "अंतर-राज्य संबंध",
  "Emergency Provisions": "आपातकालीन प्रावधान",
  "President": "राष्ट्रपति",
  "Vice-President": "उपराष्ट्रपति",
  "Prime Minister": "प्रधानमंत्री",
  "Central Council of Ministers": "केंद्रीय मंत्रिपरिषद",
  "Cabinet Committees": "मंत्रिमंडल समितियाँ",
  "Parliament": "संसद",
  "Parliamentary Committees": "संसदीय समितियाँ",
  "Parliamentary Forums": "संसदीय मंच",
  "Parliamentary Group": "संसदीय समूह",
  "Supreme Court": "सर्वोच्च न्यायालय",
  "Judicial Review": "न्यायिक पुनर्विलोकन",
  "Judicial Activism": "न्यायिक सक्रियता",
  "Public Interest Litigation": "जनहित याचिका",
  "Governor": "राज्यपाल",
  "Chief Minister": "मुख्यमंत्री",
  "State Council of Ministers": "राज्य मंत्रिपरिषद",
  "State Legislature": "राज्य विधानमंडल",
  "High Court": "उच्च न्यायालय",
  "Subordinate Courts": "अधीनस्थ न्यायालय",
  "Jammu & Kashmir (incl. Art 370 developments)": "जम्मू और कश्मीर (अनुच्छेद 370 के विकास सहित)",
  "Special Provisions for Some States": "कुछ राज्यों के लिए विशेष प्रावधान",
  "Panchayati Raj": "पंचायती राज",
  "Municipalities": "नगरपालिकाएँ",
  "Union Territories": "संघ राज्यक्षेत्र",
  "Scheduled and Tribal Areas": "अनुसूचित और जनजातीय क्षेत्र",
  "Election Commission": "निर्वाचन आयोग",
  "UPSC": "UPSC",
  "State PSC": "राज्य PSC",
  "Finance Commission": "वित्त आयोग",
  "GST Council": "GST परिषद",
  "National Commission for SCs": "अनुसूचित जातियों के लिए राष्ट्रीय आयोग",
  "National Commission for STs": "अनुसूचित जनजातियों के लिए राष्ट्रीय आयोग",
  "National Commission for BCs": "पिछड़ा वर्ग के लिए राष्ट्रीय आयोग",
  "Special Officer for Linguistic Minorities": "भाषाई अल्पसंख्यकों के लिए विशेष अधिकारी",
  "CAG": "CAG",
  "Attorney General of India": "भारत के महान्यायवादी",
  "Advocate General of the State": "राज्य के महाधिवक्ता",
  "NITI Aayog": "NITI Aayog",
  "NHRC": "NHRC",
  "SHRC": "SHRC",
  "Central Information Commission": "केंद्रीय सूचना आयोग",
  "State Information Commission": "राज्य सूचना आयोग",
  "Central Vigilance Commission": "केंद्रीय सतर्कता आयोग",
  "CBI": "CBI",
  "Lokpal and Lokayuktas": "लोकपाल और लोकायुक्त",
  "NIA": "NIA",
  "NDMA": "NDMA",
  "Co-operative Societies": "सहकारी समितियाँ",
  "Official Language": "राजभाषा",
  "Public Services": "लोक सेवाएं",
  "Rights and Liabilities of the Government": "सरकार के अधिकार और दायित्व",
  "Special Provisions Relating to Certain Classes": "कुछ वर्गों से संबंधित विशेष प्रावधान",
  "Political Parties": "राजनीतिक दल",
  "Role of Regional Parties": "क्षेत्रीय दलों की भूमिका",
  "Elections": "चुनाव",
  "Election Laws": "चुनाव कानून",
  "Electoral Reforms": "निर्वाचन सुधार",
  "Voting Behaviour": "मतदान व्यवहार",
  "Coalition Government": "गठबंधन सरकार",
  "Anti-Defection Law": "दल-बदल विरोधी कानून",
  "Pressure Groups": "दबाव समूह",
  "National Integration": "राष्ट्रीय एकीकरण",
  "Foreign Policy": "विदेश नीति",
  "Appendices + full-book PYQ sweep": "परिशिष्ट + पूर्ण-पुस्तक PYQ स्वीप",
  "The Importance of Ancient Indian History": "प्राचीन भारतीय इतिहास का महत्व",
  "The Construction of Ancient Indian History (sources)": "प्राचीन भारतीय इतिहास का निर्माण (स्रोत)",
  "The Geographical Setting": "भौगोलिक परिवेश",
  "The Stone Age": "पाषाण काल",
  "The Stone-Copper (Chalcolithic) Phase": "पाषाण-ताम्र (ताम्रपाषाण) काल",
  "The Harappan Civilization": "हड़प्पा सभ्यता",
  "Advent of the Aryans and the Age of the Rig Veda": "आर्यों का आगमन और ऋग्वैदिक काल",
  "The Later Vedic Phase: Transition to State and Social Formation": "उत्तर वैदिक काल: राज्य और सामाजिक गठन की ओर संक्रमण",
  "Jainism and Buddhism": "जैन धर्म और बौद्ध धर्म",
  "Territorial States and the First Magadhan Empire": "जनपदीय राज्य और प्रथम मगध साम्राज्य",
  "Iranian and Macedonian Invasions": "ईरानी और मैसेडोनियन आक्रमण",
  "State and Varna Society in the Age of the Buddha": "बुद्ध के काल में राज्य और वर्ण समाज",
  "The Age of the Mauryas": "मौर्य काल",
  "Significance of the Maurya Rule": "मौर्य शासन का महत्व",
  "Central Asian Contacts and Their Results": "मध्य एशियाई संपर्क और उनके परिणाम",
  "The Age of the Satavahanas": "सातवाहन काल",
  "The Dawn of History in the Deep South": "दक्षिण भारत में इतिहास का उदय",
  "Crafts, Trade and Towns in the Post-Maurya Age": "मौर्योत्तर काल में शिल्प, व्यापार और नगर",
  "The Rise and Growth of the Gupta Empire": "गुप्त साम्राज्य का उदय और विकास",
  "Life in the Gupta Age": "गुप्त काल में जीवन",
  "Spread of Civilization in Eastern India": "पूर्वी भारत में सभ्यता का प्रसार",
  "Harsha and His Times": "हर्ष और उसका काल",
  "Formation of New States and Rural Expansion in the Peninsula": "प्रायद्वीप में नए राज्यों का गठन और ग्रामीण विस्तार",
  "India's Cultural Contacts with the Asian Countries": "एशियाई देशों के साथ भारत के सांस्कृतिक संपर्क",
  "Transformation of the Ancient Phase": "प्राचीन काल का रूपांतरण",
  "Sequence of Social Changes": "सामाजिक परिवर्तनों का क्रम",
  "Legacy in Science and Civilization": "विज्ञान और सभ्यता में विरासत",
  "India and the World (8th century)": "भारत और विश्व (8वीं शताब्दी)",
  "Northern India: Age of the Three Empires (Palas, Pratiharas, Rashtrakutas)": "उत्तरी भारत: तीन साम्राज्यों का काल (पाल, प्रतिहार, राष्ट्रकूट)",
  "The Chola Empire": "चोल साम्राज्य",
  "Economic and Social Life, Education and Religious Beliefs (800–1200)": "आर्थिक और सामाजिक जीवन, शिक्षा और धार्मिक विश्वास (800–1200)",
  "The Age of Conflict (Ghaznavids and Ghurids)": "संघर्ष का काल (ग़ज़नवी और ग़ोरी)",
  "The Delhi Sultanat I (13th century)": "दिल्ली सल्तनत I (13वीं शताब्दी)",
  "The Delhi Sultanat II (Khalji and Tughlaq)": "दिल्ली सल्तनत II (ख़िलजी और तुग़लक)",
  "Government, Economic and Social Life under the Sultanat": "सल्तनत के अधीन शासन, आर्थिक और सामाजिक जीवन",
  "The Age of Vijayanagara and the Bahmanids, Coming of the Portuguese": "विजयनगर और बहमनी का काल, पुर्तगालियों का आगमन",
  "Struggle for Empire in North India I (c. 1400–1525)": "उत्तर भारत में साम्राज्य के लिए संघर्ष I (लगभग 1400–1525)",
  "Cultural Development in India (13th–15th centuries)": "भारत में सांस्कृतिक विकास (13वीं–15वीं शताब्दी)",
  "Struggle for Empire in North India II: Mughals and Afghans (1525–1555)": "उत्तर भारत में साम्राज्य के लिए संघर्ष II: मुग़ल और अफ़ग़ान (1525–1555)",
  "Consolidation of the Mughal Empire: Age of Akbar": "मुग़ल साम्राज्य का सुदृढ़ीकरण: अकबर का काल",
  "The Deccan and South India (up to 1656)": "दक्कन और दक्षिण भारत (1656 तक)",
  "India in the First Half of the Seventeenth Century": "सत्रहवीं शताब्दी के पूर्वार्ध में भारत",
  "Economic and Social Life under the Mughals": "मुगलों के अधीन आर्थिक और सामाजिक जीवन",
  "Cultural and Religious Developments": "सांस्कृतिक और धार्मिक विकास",
  "Climax and Disintegration of the Mughal Empire I": "मुगल साम्राज्य का चरमोत्कर्ष और विघटन I",
  "Climax and Disintegration II + Assessment and Review": "मुगल साम्राज्य का चरमोत्कर्ष और विघटन II + मूल्यांकन और समीक्षा",
  "The Decline of the Mughal Empire": "मुगल साम्राज्य का पतन",
  "Indian States and Society in the 18th Century": "18वीं शताब्दी में भारतीय राज्य और समाज",
  "European Penetration and the British Conquest of India": "यूरोपीय प्रवेश और भारत का ब्रिटिश विजय",
  "The Structure of Government and Economic Policies of the British Empire (1757–1857)": "ब्रिटिश साम्राज्य की सरकार की संरचना और आर्थिक नीतियां (1757-1857)",
  "Administrative Organisation and Social & Cultural Policy": "प्रशासनिक संगठन और सामाजिक एवं सांस्कृतिक नीति",
  "Social and Cultural Awakening in the First Half of the 19th Century": "19वीं शताब्दी के पूर्वार्ध में सामाजिक और सांस्कृतिक जागरण",
  "The Revolt of 1857": "1857 का विद्रोह",
  "Administrative Changes after 1858": "1858 के बाद प्रशासनिक परिवर्तन",
  "The Economic Impact of British Rule": "ब्रिटिश शासन का आर्थिक प्रभाव",
  "Growth of New India: Religious and Social Reform after 1858": "नव भारत का विकास: 1858 के बाद धार्मिक और सामाजिक सुधार",
  "The Nationalist Movement (1858–1905)": "राष्ट्रवादी आंदोलन (1858-1905)",
  "The Nationalist Movement (1905–1918)": "राष्ट्रवादी आंदोलन (1905-1918)",
  "The Struggle for Swaraj I (1919–1927)": "स्वराज के लिए संघर्ष I (1919-1927)",
  "The Struggle for Swaraj II (1927–1947)": "स्वराज के लिए संघर्ष II (1927-1947)",
  "Spectrum full-book rapid revision (chronology consolidation)": "स्पेक्ट्रम पूर्ण-पुस्तक त्वरित पुनरीक्षण (कालानुक्रमिक समेकन)",
  "Challenges of Nation Building": "राष्ट्र निर्माण की चुनौतियाँ",
  "Era of One-Party Dominance": "एक-दलीय प्रभुत्व का युग",
  "Politics of Planned Development": "नियोजित विकास की राजनीति",
  "India's External Relations": "भारत के बाह्य संबंध",
  "Challenges to and Restoration of the Congress System": "कांग्रेस प्रणाली की चुनौतियाँ और पुनर्स्थापन",
  "The Crisis of Democratic Order (Emergency)": "लोकतांत्रिक व्यवस्था का संकट (आपातकाल)",
  "Rise of Popular Movements": "लोकप्रिय आंदोलनों का उदय",
  "Regional Aspirations": "क्षेत्रीय आकांक्षाएँ",
  "Recent Developments in Indian Politics": "भारतीय राजनीति में हालिया विकास",
  "Renaissance, Reformation, Age of Exploration": "पुनर्जागरण, धर्मसुधार, अन्वेषण का युग",
  "American Revolution": "अमेरिकी क्रांति",
  "French Revolution & Napoleon": "फ्रांसीसी क्रांति और नेपोलियन",
  "Industrial Revolution": "औद्योगिक क्रांति",
  "Unification of Italy and Germany; nationalism in Europe": "इटली और जर्मनी का एकीकरण; यूरोप में राष्ट्रवाद",
  "Colonialism and imperialism in Asia & Africa": "एशिया और अफ्रीका में उपनिवेशवाद और साम्राज्यवाद",
  "World War I, Russian Revolution, Great Depression": "प्रथम विश्व युद्ध, रूसी क्रांति, महामंदी",
  "Fascism/Nazism and World War II": "फासीवाद/नाजीवाद और द्वितीय विश्व युद्ध",
  "Cold War and bipolar world": "शीत युद्ध और द्विध्रुवी विश्व",
  "Decolonization — Asia and Africa": "वि-उपनिवेशीकरण — एशिया और अफ्रीका",
  "Redrawal of national boundaries; disintegration of USSR": "राष्ट्रीय सीमाओं का पुनर्निर्धारण; सोवियत संघ का विघटन",
  "Globalization and the contemporary world": "वैश्वीकरण और समकालीन विश्व",
  "Prehistoric Rock Paintings": "प्रागैतिहासिक शैल चित्रकला",
  "Arts of the Indus Valley": "सिंधु घाटी की कलाएँ",
  "Arts of the Mauryan Period": "मौर्य काल की कलाएँ",
  "Post-Mauryan Trends in Art & Architecture": "कला और वास्तुकला में मौर्योत्तर प्रवृत्तियाँ",
  "Later Mural Traditions": "उत्तरवर्ती भित्ति चित्र परम्पराएँ",
  "Temple Architecture and Sculpture": "मंदिर वास्तुकला और मूर्तिकला",
  "Indian Bronze Sculpture": "भारतीय कांस्य मूर्तिकला",
  "Some Aspects of Indo-Islamic Architecture": "इंडो-इस्लामिक वास्तुकला के कुछ पहलू",
  "Indian Architecture: Harappan to temple styles (Nagara/Dravida/Vesara)": "भारतीय वास्तुकला: हड़प्पा से मंदिर शैलियों तक (नागर/द्रविड़/वेसर)",
  "Cave architecture": "गुफा वास्तुकला",
  "Indo-Islamic architecture": "इंडो-इस्लामिक वास्तुकला",
  "Colonial and modern architecture": "औपनिवेशिक और आधुनिक वास्तुकला",
  "Indian sculpture": "भारतीय मूर्तिकला",
  "Indian pottery": "भारतीय मृद्भांड",
  "Indian paintings (murals + miniature schools)": "भारतीय चित्रकला (भित्ति चित्र + लघु चित्र शैलियाँ)",
  "Handicrafts": "हस्तशिल्प",
  "UNESCO tangible heritage sites": "UNESCO मूर्त विरासत स्थल",
  "Indian music (Hindustani & Carnatic)": "भारतीय संगीत (हिन्दुस्तानी और कर्नाटक)",
  "Classical and folk dance": "शास्त्रीय और लोक नृत्य",
  "Theatre forms": "नाट्य रूप",
  "Puppetry": "कठपुतली",
  "Martial arts": "युद्ध कलाएँ",
  "UNESCO intangible heritage list": "UNESCO अमूर्त विरासत सूची",
  "Languages of India": "भारत की भाषाएँ",
  "Sanskrit, Pali-Prakrit and regional literature": "संस्कृत, पालि-प्राकृत और क्षेत्रीय साहित्य",
  "Religions in India": "भारत में धर्म",
  "Schools of Indian philosophy": "भारतीय दर्शन की विचारधाराएँ",
  "Bhakti and Sufi movements": "भक्ति और सूफी आंदोलन",
  "Indian cinema (brief)": "भारतीय सिनेमा (संक्षिप्त)",
  "Fairs and festivals": "मेले और त्यौहार",
  "Awards and honours": "पुरस्कार और सम्मान",
  "Law, culture institutions and current cultural affairs": "कानून, सांस्कृतिक संस्थान और समसामयिक सांस्कृतिक मामले",
  "Indian calendars": "भारतीय पंचांग",
  "Famous personalities (selective)": "प्रसिद्ध व्यक्तित्व (चयनात्मक)",
  "India — Location": "भारत — अवस्थिति",
  "Structure and Physiography": "संरचना और उच्चावच",
  "Drainage System": "अपवाह तंत्र",
  "Climate": "जलवायु",
  "Natural Vegetation": "प्राकृतिक वनस्पति",
  "Soils of India (MD Notes supplement)": "भारत की मृदाएँ (एमडी नोट्स पूरक)",
  "Natural Hazards and Disasters": "प्राकृतिक संकट और आपदाएँ",
  "India physical map consolidation test": "भारत भौतिक मानचित्र समेकन परीक्षण",
  "Population: Distribution, Density, Growth": "जनसंख्या: वितरण, घनत्व, वृद्धि",
  "Migration": "प्रवास",
  "Human Development": "मानव विकास",
  "Human Settlements": "मानव बस्तियाँ",
  "Land Resources and Agriculture": "भूमि संसाधन और कृषि",
  "Water Resources": "जल संसाधन",
  "Mineral and Energy Resources": "खनिज और ऊर्जा संसाधन",
  "Manufacturing Industries": "विनिर्माण उद्योग",
  "Planning and Sustainable Development": "नियोजन और सतत विकास",
  "Transport and Communication": "परिवहन और संचार",
  "International Trade": "अंतर्राष्ट्रीय व्यापार",
  "Geographical Perspective on Selected Issues": "चयनित मुद्दों पर भौगोलिक परिप्रेक्ष्य",
  "Geography as a Discipline": "एक अनुशासन के रूप में भूगोल",
  "The Origin and Evolution of the Earth": "पृथ्वी की उत्पत्ति और विकास",
  "Interior of the Earth": "पृथ्वी का आंतरिक भाग",
  "Distribution of Oceans and Continents (plate tectonics)": "महासागरों और महाद्वीपों का वितरण (प्लेट टेक्टोनिक्स)",
  "Minerals and Rocks": "खनिज और चट्टानें",
  "Geomorphic Processes": "भू-आकृतिक प्रक्रियाएँ",
  "Landforms and their Evolution": "स्थलाकृतियाँ और उनका विकास",
  "Composition and Structure of Atmosphere": "वायुमंडल की संरचना और संघटन",
  "Solar Radiation, Heat Balance and Temperature": "सौर विकिरण, ऊष्मा संतुलन और तापमान",
  "Atmospheric Circulation and Weather Systems": "वायुमंडलीय परिसंचरण और मौसम प्रणालियाँ",
  "Water in the Atmosphere": "वायुमंडल में जल",
  "G.C. Leong — pressure belts, winds, cyclones": "जी.सी. लियोंग — दाब पेटियाँ, पवनें, चक्रवात",
  "World Climate and Climate Change": "विश्व जलवायु और जलवायु परिवर्तन",
  "G.C. Leong — climate types (Koppen regions)": "जी.सी. लियोंग — जलवायु के प्रकार (कोपेन क्षेत्र)",
  "Water (Oceans)": "जल (महासागर)",
  "Movements of Ocean Water": "महासागरीय जल की गतियाँ",
  "Life on the Earth": "पृथ्वी पर जीवन",
  "Biodiversity and Conservation": "जैव विविधता और संरक्षण",
  "Human Geography: Nature and Scope": "मानव भूगोल: प्रकृति और दायरा",
  "The World Population: Distribution, Density and Growth": "विश्व जनसंख्या: वितरण, घनत्व और वृद्धि",
  "Population Composition": "जनसंख्या की संरचना",
  "Primary Activities": "प्राथमिक गतिविधियाँ",
  "Secondary Activities": "द्वितीयक गतिविधियाँ",
  "Tertiary and Quaternary Activities": "तृतीयक और चतुर्थक गतिविधियाँ",
  "Continent-wise physical mapping (7 sittings)": "महाद्वीपों के अनुसार भौतिक मानचित्रण (7 बैठकें)",
  "Strategic locations, straits, canals, current-affairs places": "सामरिक स्थान, जलडमरूमध्य, नहरें, सामयिक मामले वाले स्थान",
  "Economics and the Economy (concepts, sectors, national income)": "अर्थशास्त्र और अर्थव्यवस्था (अवधारणाएँ, क्षेत्र, राष्ट्रीय आय)",
  "Introduction to Economics": "अर्थशास्त्र का परिचय",
  "National Income": "राष्ट्रीय आय",
  "Growth, Development and Happiness": "विकास, प्रगति और खुशी",
  "Evolution of the Indian Economy": "भारतीय अर्थव्यवस्था का विकास",
  "Economic Planning": "आर्थिक नियोजन",
  "Planning in India": "भारत में नियोजन",
  "Planning in India (incl. NITI Aayog)": "भारत में नियोजन (नीति आयोग सहित)",
  "Economic Reforms": "आर्थिक सुधार",
  "Economic Reforms (LPG)": "आर्थिक सुधार (एलपीजी)",
  "Inflation and Business Cycle": "मुद्रास्फीति और व्यावसायिक चक्र",
  "Agriculture and Food Management": "कृषि और खाद्य प्रबंधन",
  "Industry and Infrastructure": "उद्योग और अवसंरचना",
  "Industry and Infrastructure-linked policy": "उद्योग और अवसंरचना-लिंक्ड नीति",
  "Services Sector": "सेवा क्षेत्र",
  "Indian Financial Market": "भारतीय वित्तीय बाज़ार",
  "Infrastructure (energy, transport, PPP models)": "अवसंरचना (ऊर्जा, परिवहन, पीपीपी मॉडल)",
  "Banking in India": "भारत में बैंकिंग",
  "Banking and the Monetary System": "बैंकिंग और मौद्रिक प्रणाली",
  "Insurance in India": "भारत में बीमा",
  "Security Market in India": "भारत में प्रतिभूति बाज़ार",
  "Security Markets in India": "भारत में प्रतिभूति बाजार",
  "External Sector in India": "भारत में बाह्य क्षेत्र",
  "External Sector in India (BoP, exchange rate, trade policy)": "भारत में बाह्य क्षेत्र (भुगतान संतुलन, विनिमय दर, व्यापार नीति)",
  "International Economic Organisations and India": "अंतर्राष्ट्रीय आर्थिक संगठन और भारत",
  "International Economic Organisations and India (IMF, WB, WTO)": "अंतर्राष्ट्रीय आर्थिक संगठन और भारत (आईएमएफ, विश्व बैंक, डब्ल्यूटीओ)",
  "Tax Structure in India": "भारत में कर संरचना",
  "Tax Structure in India (incl. GST)": "भारत में कर संरचना (जीएसटी सहित)",
  "Public Finance in India": "भारत में लोक वित्त",
  "Public Finance in India (budget, deficits, FRBM)": "भारत में लोक वित्त (बजट, घाटे, एफआरबीएम)",
  "Sustainability and Climate Change: India and the World": "स्थिरता और जलवायु परिवर्तन: भारत और विश्व",
  "Human Development in India": "भारत में मानव विकास",
  "Burning Socio-Economic Issues": "ज्वलंत सामाजिक-आर्थिक मुद्दे",
  "Economic Survey": "आर्थिक सर्वेक्षण",
  "Union Budget": "केंद्रीय बजट",
  "Economic Concepts and Terminologies (glossary sweep)": "आर्थिक अवधारणाएँ और शब्दावली (शब्दावली समीक्षा)",
  "Economic Survey — key chapters of the year": "आर्थिक सर्वेक्षण — वर्ष के मुख्य अध्याय",
  "Ecology — organism and environment": "पारिस्थितिकी — जीव और पर्यावरण",
  "Ecosystem functions (energy flow, cycles)": "पारिस्थितिकी तंत्र के कार्य (ऊर्जा प्रवाह, चक्र)",
  "Terrestrial ecosystems": "स्थलीय पारिस्थितिकी तंत्र",
  "Aquatic ecosystems": "जलीय पारिस्थितिकी तंत्र",
  "Biodiversity — concepts and measurement": "जैव विविधता — अवधारणाएँ और मापन",
  "Indian biodiversity and hotspots": "भारतीय जैव विविधता और हॉटस्पॉट",
  "Plant and animal diversity (IUCN categories)": "पादप और जंतु विविधता (आईयूसीएन श्रेणियाँ)",
  "Marine and coastal biodiversity": "समुद्री और तटीय जैव विविधता",
  "Protected Area Network (NP, WLS, BR, community reserves)": "संरक्षित क्षेत्र नेटवर्क (राष्ट्रीय उद्यान, वन्यजीव अभयारण्य, बायोस्फीयर रिजर्व, सामुदायिक रिजर्व)",
  "Conservation efforts — species programmes (Tiger, Elephant, etc.)": "संरक्षण प्रयास — प्रजाति कार्यक्रम (बाघ, हाथी, आदि)",
  "International conservation conventions (CBD, CITES, Ramsar)": "अंतर्राष्ट्रीय संरक्षण सम्मेलन (सीबीडी, साइट्स, रामसर)",
  "Wetlands and Ramsar sites in India": "भारत में आर्द्रभूमियाँ और रामसर स्थल",
  "Climate change science": "जलवायु परिवर्तन विज्ञान",
  "Impacts and vulnerability": "प्रभाव और भेद्यता",
  "Global initiatives — UNFCCC, Kyoto, Paris": "वैश्विक पहल — यूएनएफसीसीसी, क्योटो, पेरिस",
  "India's climate commitments and missions (NAPCC, NDC)": "भारत की जलवायु प्रतिबद्धताएँ और मिशन (एनएपीसी, एनडीसी)",
  "Air pollution (incl. NCAP)": "वायु प्रदूषण (एनसीएपी सहित)",
  "Water pollution": "जल प्रदूषण",
  "Soil, noise, thermal pollution": "मृदा, ध्वनि, तापीय प्रदूषण",
  "Waste management (solid, e-waste, plastic rules)": "अपशिष्ट प्रबंधन (ठोस, ई-कचरा, प्लास्टिक नियम)",
  "Environmental legislation (EPA, Air Act, Water Act, WPA, FCA)": "पर्यावरणीय विधान (EPA, वायु अधिनियम, जल अधिनियम, WPA, FCA)",
  "Institutions — CPCB, NGT, NBWL, etc.": "संस्थान — CPCB, NGT, NBWL, आदि।",
  "Environmental Impact Assessment": "पर्यावरणीय प्रभाव आकलन",
  "Forest rights and forest governance (FRA, CAMPA)": "वन अधिकार और वन शासन (FRA, CAMPA)",
  "Sustainable agriculture and organic farming": "सतत कृषि और जैविक खेती",
  "Renewable energy and energy environment": "नवीकरणीय ऊर्जा और ऊर्जा पर्यावरण",
  "Sustainable development and green economy": "सतत विकास और हरित अर्थव्यवस्था",
  "Disasters with environmental dimension": "आपदाएं जिनका पर्यावरणीय आयाम हो",
  "Geo-environmental issues in news": "भू-पर्यावरणीय मुद्दे समाचारों में",
  "Species/places in news — annual compilation": "प्रजातियाँ/स्थान समाचारों में — वार्षिक संकलन",
  "Evolution of India's foreign policy (NAM to multi-alignment)": "भारत की विदेश नीति का विकास (गुटनिरपेक्ष आंदोलन से बहु-संरेखण तक)",
  "Doctrines, principles and institutions (MEA, Panchsheel, Gujral etc.)": "सिद्धांत, सिद्धांत और संस्थान (MEA, पंचशील, गुजराल आदि)",
  "India–Pakistan": "भारत-पाकिस्तान",
  "India–Afghanistan": "भारत-अफगानिस्तान",
  "India–China": "भारत-चीन",
  "India–Nepal": "भारत-नेपाल",
  "India–Bhutan": "भारत-भूटान",
  "India–Bangladesh": "भारत-बांग्लादेश",
  "India–Sri Lanka": "भारत-श्रीलंका",
  "India–Myanmar": "भारत-म्यांमार",
  "India–Maldives": "भारत-मालदीव",
  "India–USA": "भारत-संयुक्त राज्य अमेरिका",
  "India–Russia": "भारत-रूस",
  "India–Japan, Australia, South Korea": "भारत-जापान, ऑस्ट्रेलिया, दक्षिण कोरिया",
  "ASEAN and Act East": "आसियान और एक्ट ईस्ट",
  "Indo-Pacific and QUAD": "इंडो-पैसिफिक और QUAD",
  "India–West Asia (Israel, Iran, Gulf)": "भारत-पश्चिम एशिया (इज़राइल, ईरान, खाड़ी)",
  "India–Africa": "भारत-अफ्रीका",
  "India–Central Asia, Latin America, Europe/EU": "भारत-मध्य एशिया, लैटिन अमेरिका, यूरोप/ईयू",
  "UN and UNSC reform": "संयुक्त राष्ट्र और UNSC सुधार",
  "Groupings — BRICS, SCO, G20, IBSA, etc.": "समूह — BRICS, SCO, G20, IBSA, आदि।",
  "Nuclear policy and export-control regimes": "परमाणु नीति और निर्यात-नियंत्रण व्यवस्था",
  "Diaspora, soft power, international law basics": "प्रवासी, सॉफ्ट पावर, अंतर्राष्ट्रीय कानून की मूल बातें",
  "Concepts: internal vs external security, linkages": "अवधारणाएँ: आंतरिक बनाम बाहरी सुरक्षा, जुड़ाव",
  "Security architecture of India (agencies, forces, coordination)": "भारत की सुरक्षा वास्तुकला (एजेंसियां, बल, समन्वय)",
  "Jammu & Kashmir militancy — evolution and current phase": "जम्मू और कश्मीर में आतंकवाद — विकास और वर्तमान चरण",
  "Cross-border terrorism and state sponsorship": "सीमा पार आतंकवाद और राज्य प्रायोजन",
  "North-East — group-wise insurgency map": "पूर्वोत्तर — समूह-वार उग्रवाद का नक्शा",
  "Peace accords and AFSPA debate": "शांति समझौते और AFSPA बहस",
  "LWE — origins, spread, current status": "LWE — उत्पत्ति, प्रसार, वर्तमान स्थिति",
  "Government response — security + development approach (SAMADHAN)": "सरकारी प्रतिक्रिया — सुरक्षा + विकास दृष्टिकोण (SAMADHAN)",
  "Terrorism — typologies, financing, radicalisation": "आतंकवाद — प्रकार, वित्तपोषण, ध्रुवीकरण",
  "Organised crime — linkages with terrorism, money laundering (PMLA, FATF)": "संगठित अपराध — आतंकवाद से संबंध, धन शोधन (PMLA, FATF)",
  "Cyber security — threats, architecture (CERT-In, NCIIPC)": "साइबर सुरक्षा — खतरे, वास्तुकला (CERT-In, NCIIPC)",
  "Role of media, social media and communication networks in security": "सुरक्षा में मीडिया, सोशल मीडिया और संचार नेटवर्क की भूमिका",
  "Border management — land borders, coastal security": "सीमा प्रबंधन — भूमि सीमाएँ, तटीय सुरक्षा",
  "Security forces — CAPFs, police reforms, private security": "सुरक्षा बल — CAPFs, पुलिस सुधार, निजी सुरक्षा",
  "DM Act 2005, NDMA framework, NDMP": "DM Act 2005, NDMA ढाँचा, NDMP",
  "2nd ARC — Crisis Management (key recommendations)": "2nd ARC — संकट प्रबंधन (मुख्य सिफारिशें)",
  "Sendai framework; case studies — cyclone, flood, industrial": "सेंडई ढाँचा; केस स्टडीज़ — चक्रवात, बाढ़, औद्योगिक",
  "Features of Indian society; unity in diversity": "भारतीय समाज की विशेषताएँ; विविधता में एकता",
  "Family, kinship, marriage — forms and change": "परिवार, नातेदारी, विवाह — रूप और परिवर्तन",
  "Regionalism and diversity management": "क्षेत्रवाद और विविधता प्रबंधन",
  "Caste system — continuity and change": "जाति व्यवस्था — निरंतरता और परिवर्तन",
  "Tribes — issues and policy": "जनजाति — मुद्दे और नीति",
  "Religion, communalism, secularism": "धर्म, सांप्रदायिकता, धर्मनिरपेक्षता",
  "Demography and population issues": "जनसांख्यिकी और जनसंख्या मुद्दे",
  "Women — status, patriarchy, violence, empowerment": "महिलाएँ — स्थिति, पितृसत्ता, हिंसा, सशक्तिकरण",
  "Urbanization and migration — social effects": "शहरीकरण और प्रवासन — सामाजिक प्रभाव",
  "Globalization — social effects": "वैश्वीकरण — सामाजिक प्रभाव",
  "Poverty and developmental issues": "गरीबी और विकासात्मक मुद्दे",
  "Social empowerment and social movements": "सामाजिक सशक्तिकरण और सामाजिक आंदोलन",
  "Governance vs government; good governance indicators": "शासन बनाम सरकार; सुशासन संकेतक",
  "Accountability and transparency — RTI (ARC 1st Report)": "जवाबदेही और पारदर्शिता — RTI (ARC 1st Report)",
  "Citizens' charters and grievance redressal": "नागरिक चार्टर और शिकायत निवारण",
  "2nd ARC — Ethics in Governance (key recommendations)": "2nd ARC — शासन में नैतिकता (मुख्य सिफारिशें)",
  "2nd ARC — Citizen Centric Administration": "2nd ARC — नागरिक केंद्रित प्रशासन",
  "Social audit and participatory governance": "सामाजिक अंकेक्षण और सहभागी शासन",
  "2nd ARC — Promoting e-Governance; Digital India stack": "2nd ARC — ई-गवर्नेंस को बढ़ावा देना; डिजिटल इंडिया स्टैक",
  "Role of civil services in democracy; reforms (Mission Karmayogi)": "लोकतंत्र में सिविल सेवाओं की भूमिका; सुधार (मिशन कर्मयोगी)",
  "Institutional and regulatory bodies overview": "संस्थागत और नियामक निकायों का अवलोकन",
  "SHGs, NGOs, cooperatives — role in development": "SHGs, NGOs, सहकारी समितियाँ — विकास में भूमिका",
  "Government schemes — architecture and evaluation framework": "सरकारी योजनाएँ — वास्तुकला और मूल्यांकन ढाँचा",
  "Bills and acts tracking method (PRS-based)": "विधेयकों और अधिनियमों की ट्रैकिंग विधि (PRS-आधारित)",
  "SC/ST/OBC — constitutional + scheme architecture": "SC/ST/OBC — संवैधानिक + योजना वास्तुकला",
  "Minorities, disabled, elderly, children, transgender persons": "अल्पसंख्यक, विकलांग, बुजुर्ग, बच्चे, ट्रांसजेंडर व्यक्ति",
  "Related bodies and commissions": "संबंधित निकाय और आयोग",
  "Health — policy, Ayushman Bharat, nutrition (POSHAN)": "स्वास्थ्य — नीति, आयुष्मान भारत, पोषण (POSHAN)",
  "Education — NEP 2020, schemes, issues": "शिक्षा — NEP 2020, योजनाएं, मुद्दे",
  "Skill development and employment programmes": "कौशल विकास और रोजगार कार्यक्रम",
  "Poverty and hunger — measurement and debates": "गरीबी और भुखमरी — मापन और बहसें",
  "Flagship welfare schemes — design and implementation issues": "प्रमुख कल्याणकारी योजनाएं — डिजाइन और कार्यान्वयन के मुद्दे",
  "DBT, targeting vs universalisation debates": "DBT, लक्ष्यीकरण बनाम सार्वभौमिकरण बहसें",
  "Essence, determinants and consequences of ethics": "नैतिकता का सार, निर्धारक और परिणाम",
  "Dimensions of ethics; ethics in private and public relationships": "नैतिकता के आयाम; निजी और सार्वजनिक संबंधों में नैतिकता",
  "Human values — lessons from lives of leaders and reformers": "मानवीय मूल्य — नेताओं और सुधारकों के जीवन से सीख",
  "Attitude — content, structure, function; moral and political attitudes": "अभिवृत्ति — सामग्री, संरचना, कार्य; नैतिक और राजनीतिक अभिवृत्तियाँ",
  "Aptitude and foundational values for civil service": "सिविल सेवा के लिए अभिरुचि और मूलभूत मूल्य",
  "Integrity, impartiality, objectivity, dedication, empathy, compassion": "ईमानदारी, निष्पक्षता, वस्तुनिष्ठता, समर्पण, सहानुभूति, करुणा",
  "Emotional intelligence — concepts and application": "भावनात्मक बुद्धिमत्ता — अवधारणाएं और अनुप्रयोग",
  "Moral thinkers and philosophers — India and world": "नैतिक विचारक और दार्शनिक — भारत और विश्व",
  "Public/civil service values and ethics in public administration": "सार्वजनिक/सिविल सेवा मूल्य और लोक प्रशासन में नैतिकता",
  "Ethical dilemmas, conscience, accountability sources": "नैतिक दुविधाएं, अंतरात्मा, जवाबदेही के स्रोत",
  "Laws, rules, regulations as sources of ethical guidance": "कानून, नियम, विनियम नैतिक मार्गदर्शन के स्रोत के रूप में",
  "Probity in governance — concept and philosophical basis": "शासन में सत्यनिष्ठा — अवधारणा और दार्शनिक आधार",
  "Codes of ethics/conduct, citizen charters, work culture": "नैतिकता/आचरण संहिता, नागरिक चार्टर, कार्य संस्कृति",
  "Challenges of corruption; RTI and transparency": "भ्रष्टाचार की चुनौतियाँ; RTI और पारदर्शिता",
  "Case-study answer framework (stakeholders → options → evaluation → action)": "केस-स्टडी उत्तर ढाँचा (हितधारक → विकल्प → मूल्यांकन → कार्रवाई)",
  "Practice: 12 graded case studies with model structures": "अभ्यास: मॉडल संरचनाओं के साथ 12 वर्गीकृत केस स्टडीज",
  "Physics basics in exam context (optics, waves, nuclear)": "भौतिकी मूल बातें (परीक्षा संदर्भ में) (प्रकाशिकी, तरंगें, नाभिकीय)",
  "Chemistry in everyday life (materials, polymers)": "रोजमर्रा की जिंदगी में रसायन विज्ञान (सामग्री, पॉलिमर)",
  "Biology basics (cell, genetics, diseases, immunity)": "जीव विज्ञान मूल बातें (कोशिका, आनुवंशिकी, रोग, प्रतिरक्षा)",
  "Space — ISRO missions, launch vehicles, applications": "अंतरिक्ष — ISRO मिशन, प्रक्षेपण यान, अनुप्रयोग",
  "Defence technology — missiles, platforms, DRDO": "रक्षा प्रौद्योगिकी — मिसाइलें, प्लेटफॉर्म, DRDO",
  "Nuclear energy and programme": "परमाणु ऊर्जा और कार्यक्रम",
  "IT, AI/ML, robotics": "IT, AI/ML, रोबोटिक्स",
  "Telecom (5G/6G), quantum technologies, blockchain": "दूरसंचार (5G/6G), क्वांटम प्रौद्योगिकियां, ब्लॉकचेन",
  "Semiconductors and emerging tech policy": "सेमीकंडक्टर और उभरती प्रौद्योगिकी नीति",
  "Biotechnology — applications and issues": "जैव प्रौद्योगिकी — अनुप्रयोग और मुद्दे",
  "Health technologies, vaccines, gene editing": "स्वास्थ्य प्रौद्योगिकियां, टीके, जीन संपादन",
  "IPR regime and S&T policy in India": "IPR व्यवस्था और भारत में S&T नीति"
};

export const CHAPTER_NAME_HI_BY_KEY = {
  "P1|1": "ऐतिहासिक पृष्ठभूमि",
  "P1|2": "संविधान का निर्माण",
  "P1|3": "संविधान की मुख्य विशेषताएँ",
  "P1|4": "संविधान की प्रस्तावना",
  "P1|5": "संघ और उसका राज्यक्षेत्र",
  "P2|6": "नागरिकता",
  "P2|7": "मौलिक अधिकार",
  "P2|8": "राज्य के नीति निदेशक तत्व",
  "P2|9": "मौलिक कर्तव्य",
  "P2|10": "संविधान का संशोधन",
  "P3|11": "संविधान की मूल संरचना",
  "P3|12": "संसदीय प्रणाली",
  "P3|13": "संघीय प्रणाली",
  "P3|14": "केंद्र-राज्य संबंध",
  "P3|15": "अंतर-राज्य संबंध",
  "P4|16": "आपातकालीन प्रावधान",
  "P4|17": "राष्ट्रपति",
  "P4|18": "उपराष्ट्रपति",
  "P4|19": "प्रधानमंत्री",
  "P4|20": "केंद्रीय मंत्रिपरिषद",
  "P5|21": "मंत्रिमंडल समितियाँ",
  "P5|22": "संसद",
  "P5|23": "संसदीय समितियाँ",
  "P5|24": "संसदीय मंच",
  "P5|25": "संसदीय समूह",
  "P6|26": "सर्वोच्च न्यायालय",
  "P6|27": "न्यायिक पुनर्विलोकन",
  "P6|28": "न्यायिक सक्रियता",
  "P6|29": "जनहित याचिका",
  "P6|30": "राज्यपाल",
  "P7|31": "मुख्यमंत्री",
  "P7|32": "राज्य मंत्रिपरिषद",
  "P7|33": "राज्य विधानमंडल",
  "P7|34": "उच्च न्यायालय",
  "P7|35": "अधीनस्थ न्यायालय",
  "P8|36": "जम्मू और कश्मीर (अनुच्छेद 370 के विकास सहित)",
  "P8|37": "कुछ राज्यों के लिए विशेष प्रावधान",
  "P8|38": "पंचायती राज",
  "P8|39": "नगरपालिकाएँ",
  "P8|40": "संघ राज्यक्षेत्र",
  "P9|41": "अनुसूचित और जनजातीय क्षेत्र",
  "P9|42": "निर्वाचन आयोग",
  "P9|43": "UPSC",
  "P9|44": "राज्य PSC",
  "P9|45": "वित्त आयोग",
  "P10|46": "GST परिषद",
  "P10|47": "अनुसूचित जातियों के लिए राष्ट्रीय आयोग",
  "P10|48": "अनुसूचित जनजातियों के लिए राष्ट्रीय आयोग",
  "P10|49": "पिछड़ा वर्ग के लिए राष्ट्रीय आयोग",
  "P10|50": "भाषाई अल्पसंख्यकों के लिए विशेष अधिकारी",
  "P11|51": "CAG",
  "P11|52": "भारत के महान्यायवादी",
  "P11|53": "राज्य के महाधिवक्ता",
  "P11|54": "NITI Aayog",
  "P11|55": "NHRC",
  "P12|56": "SHRC",
  "P12|57": "केंद्रीय सूचना आयोग",
  "P12|58": "राज्य सूचना आयोग",
  "P12|59": "केंद्रीय सतर्कता आयोग",
  "P12|60": "CBI",
  "P13|61": "लोकपाल और लोकायुक्त",
  "P13|62": "NIA",
  "P13|63": "NDMA",
  "P13|64": "सहकारी समितियाँ",
  "P13|65": "राजभाषा",
  "P14|66": "लोक सेवाएं",
  "P14|67": "सरकार के अधिकार और दायित्व",
  "P14|68": "कुछ वर्गों से संबंधित विशेष प्रावधान",
  "P14|69": "राजनीतिक दल",
  "P14|70": "क्षेत्रीय दलों की भूमिका",
  "P15|71": "चुनाव",
  "P15|72": "चुनाव कानून",
  "P15|73": "निर्वाचन सुधार",
  "P15|74": "मतदान व्यवहार",
  "P15|75": "गठबंधन सरकार",
  "P16|76": "दल-बदल विरोधी कानून",
  "P16|77": "दबाव समूह",
  "P16|78": "राष्ट्रीय एकीकरण",
  "P16|79": "विदेश नीति",
  "P16|80": "परिशिष्ट + पूर्ण-पुस्तक PYQ स्वीप",
  "A1|1": "प्राचीन भारतीय इतिहास का महत्व",
  "A1|2": "प्राचीन भारतीय इतिहास का निर्माण (स्रोत)",
  "A1|3": "भौगोलिक परिवेश",
  "A1|4": "पाषाण काल",
  "A1|5": "पाषाण-ताम्र (ताम्रपाषाण) काल",
  "A2|6": "हड़प्पा सभ्यता",
  "A2|7": "आर्यों का आगमन और ऋग्वैदिक काल",
  "A2|8": "उत्तर वैदिक काल: राज्य और सामाजिक गठन की ओर संक्रमण",
  "A3|9": "जैन धर्म और बौद्ध धर्म",
  "A3|10": "जनपदीय राज्य और प्रथम मगध साम्राज्य",
  "A3|11": "ईरानी और मैसेडोनियन आक्रमण",
  "A3|12": "बुद्ध के काल में राज्य और वर्ण समाज",
  "A4|13": "मौर्य काल",
  "A4|14": "मौर्य शासन का महत्व",
  "A4|15": "मध्य एशियाई संपर्क और उनके परिणाम",
  "A5|16": "सातवाहन काल",
  "A5|17": "दक्षिण भारत में इतिहास का उदय",
  "A5|18": "मौर्योत्तर काल में शिल्प, व्यापार और नगर",
  "A6|19": "गुप्त साम्राज्य का उदय और विकास",
  "A6|20": "गुप्त काल में जीवन",
  "A6|21": "पूर्वी भारत में सभ्यता का प्रसार",
  "A6|22": "हर्ष और उसका काल",
  "A7|23": "प्रायद्वीप में नए राज्यों का गठन और ग्रामीण विस्तार",
  "A7|24": "एशियाई देशों के साथ भारत के सांस्कृतिक संपर्क",
  "A7|25": "प्राचीन काल का रूपांतरण",
  "A7|26": "सामाजिक परिवर्तनों का क्रम",
  "A7|27": "विज्ञान और सभ्यता में विरासत",
  "M1|1": "भारत और विश्व (8वीं शताब्दी)",
  "M1|2": "उत्तरी भारत: तीन साम्राज्यों का काल (पाल, प्रतिहार, राष्ट्रकूट)",
  "M1|3": "चोल साम्राज्य",
  "M2|4": "आर्थिक और सामाजिक जीवन, शिक्षा और धार्मिक विश्वास (800–1200)",
  "M2|5": "संघर्ष का काल (ग़ज़नवी और ग़ोरी)",
  "M3|6": "दिल्ली सल्तनत I (13वीं शताब्दी)",
  "M3|7": "दिल्ली सल्तनत II (ख़िलजी और तुग़लक)",
  "M4|8": "सल्तनत के अधीन शासन, आर्थिक और सामाजिक जीवन",
  "M4|9": "विजयनगर और बहमनी का काल, पुर्तगालियों का आगमन",
  "M5|10": "उत्तर भारत में साम्राज्य के लिए संघर्ष I (लगभग 1400–1525)",
  "M5|11": "भारत में सांस्कृतिक विकास (13वीं–15वीं शताब्दी)",
  "M6|12": "उत्तर भारत में साम्राज्य के लिए संघर्ष II: मुग़ल और अफ़ग़ान (1525–1555)",
  "M6|13": "मुग़ल साम्राज्य का सुदृढ़ीकरण: अकबर का काल",
  "M7|14": "दक्कन और दक्षिण भारत (1656 तक)",
  "M7|15": "सत्रहवीं शताब्दी के पूर्वार्ध में भारत",
  "M8|16": "मुगलों के अधीन आर्थिक और सामाजिक जीवन",
  "M8|17": "सांस्कृतिक और धार्मिक विकास",
  "M9|18": "मुगल साम्राज्य का चरमोत्कर्ष और विघटन I",
  "M9|19": "मुगल साम्राज्य का चरमोत्कर्ष और विघटन II + मूल्यांकन और समीक्षा",
  "MO1|1": "मुगल साम्राज्य का पतन",
  "MO1|2": "18वीं शताब्दी में भारतीय राज्य और समाज",
  "MO2|3": "यूरोपीय प्रवेश और भारत का ब्रिटिश विजय",
  "MO2|4": "ब्रिटिश साम्राज्य की सरकार की संरचना और आर्थिक नीतियां (1757-1857)",
  "MO3|5": "प्रशासनिक संगठन और सामाजिक एवं सांस्कृतिक नीति",
  "MO3|6": "19वीं शताब्दी के पूर्वार्ध में सामाजिक और सांस्कृतिक जागरण",
  "MO4|7": "1857 का विद्रोह",
  "MO4|8": "1858 के बाद प्रशासनिक परिवर्तन",
  "MO5|9": "ब्रिटिश शासन का आर्थिक प्रभाव",
  "MO5|10": "नव भारत का विकास: 1858 के बाद धार्मिक और सामाजिक सुधार",
  "MO6|11": "राष्ट्रवादी आंदोलन (1858-1905)",
  "MO7|12": "राष्ट्रवादी आंदोलन (1905-1918)",
  "MO7|13": "स्वराज के लिए संघर्ष I (1919-1927)",
  "MO8|14": "स्वराज के लिए संघर्ष II (1927-1947)",
  "MO8|R": "स्पेक्ट्रम पूर्ण-पुस्तक त्वरित पुनरीक्षण (कालानुक्रमिक समेकन)",
  "PI1|1": "राष्ट्र निर्माण की चुनौतियाँ",
  "PI1|2": "एक-दलीय प्रभुत्व का युग",
  "PI1|3": "नियोजित विकास की राजनीति",
  "PI2|4": "भारत के बाह्य संबंध",
  "PI2|5": "कांग्रेस प्रणाली की चुनौतियाँ और पुनर्स्थापन",
  "PI2|6": "लोकतांत्रिक व्यवस्था का संकट (आपातकाल)",
  "PI3|7": "लोकप्रिय आंदोलनों का उदय",
  "PI3|8": "क्षेत्रीय आकांक्षाएँ",
  "PI3|9": "भारतीय राजनीति में हालिया विकास",
  "WH1|1": "पुनर्जागरण, धर्मसुधार, अन्वेषण का युग",
  "WH1|2": "अमेरिकी क्रांति",
  "WH1|3": "फ्रांसीसी क्रांति और नेपोलियन",
  "WH1|4": "औद्योगिक क्रांति",
  "WH2|5": "इटली और जर्मनी का एकीकरण; यूरोप में राष्ट्रवाद",
  "WH2|6": "एशिया और अफ्रीका में उपनिवेशवाद और साम्राज्यवाद",
  "WH2|7": "प्रथम विश्व युद्ध, रूसी क्रांति, महामंदी",
  "WH2|8": "फासीवाद/नाजीवाद और द्वितीय विश्व युद्ध",
  "WH3|9": "शीत युद्ध और द्विध्रुवी विश्व",
  "WH3|10": "वि-उपनिवेशीकरण — एशिया और अफ्रीका",
  "WH3|11": "राष्ट्रीय सीमाओं का पुनर्निर्धारण; सोवियत संघ का विघटन",
  "WH3|12": "वैश्वीकरण और समकालीन विश्व",
  "AC1|1": "प्रागैतिहासिक शैल चित्रकला",
  "AC1|2": "सिंधु घाटी की कलाएँ",
  "AC1|3": "मौर्य काल की कलाएँ",
  "AC1|4": "कला और वास्तुकला में मौर्योत्तर प्रवृत्तियाँ",
  "AC1|5": "उत्तरवर्ती भित्ति चित्र परम्पराएँ",
  "AC1|6": "मंदिर वास्तुकला और मूर्तिकला",
  "AC1|7": "भारतीय कांस्य मूर्तिकला",
  "AC1|8": "इंडो-इस्लामिक वास्तुकला के कुछ पहलू",
  "AC2|1": "भारतीय वास्तुकला: हड़प्पा से मंदिर शैलियों तक (नागर/द्रविड़/वेसर)",
  "AC2|2": "गुफा वास्तुकला",
  "AC2|3": "इंडो-इस्लामिक वास्तुकला",
  "AC2|4": "औपनिवेशिक और आधुनिक वास्तुकला",
  "AC3|5": "भारतीय मूर्तिकला",
  "AC3|6": "भारतीय मृद्भांड",
  "AC3|7": "भारतीय चित्रकला (भित्ति चित्र + लघु चित्र शैलियाँ)",
  "AC3|8": "हस्तशिल्प",
  "AC3|9": "UNESCO मूर्त विरासत स्थल",
  "AC4|10": "भारतीय संगीत (हिन्दुस्तानी और कर्नाटक)",
  "AC4|11": "शास्त्रीय और लोक नृत्य",
  "AC4|12": "नाट्य रूप",
  "AC4|13": "कठपुतली",
  "AC4|14": "युद्ध कलाएँ",
  "AC4|15": "UNESCO अमूर्त विरासत सूची",
  "AC5|16": "भारत की भाषाएँ",
  "AC5|17": "संस्कृत, पालि-प्राकृत और क्षेत्रीय साहित्य",
  "AC5|18": "भारत में धर्म",
  "AC5|19": "भारतीय दर्शन की विचारधाराएँ",
  "AC5|20": "भक्ति और सूफी आंदोलन",
  "AC5|21": "भारतीय सिनेमा (संक्षिप्त)",
  "AC6|22": "मेले और त्यौहार",
  "AC6|23": "पुरस्कार और सम्मान",
  "AC6|24": "कानून, सांस्कृतिक संस्थान और समसामयिक सांस्कृतिक मामले",
  "AC6|25": "भारतीय पंचांग",
  "AC6|26": "प्रसिद्ध व्यक्तित्व (चयनात्मक)",
  "IG1|1": "भारत — अवस्थिति",
  "IG1|2": "संरचना और उच्चावच",
  "IG2|3": "अपवाह तंत्र",
  "IG3|4": "जलवायु",
  "IG3|5": "प्राकृतिक वनस्पति",
  "IG3|+": "भारत की मृदाएँ (एमडी नोट्स पूरक)",
  "IG4|6": "प्राकृतिक संकट और आपदाएँ",
  "IG4|+": "भारत भौतिक मानचित्र समेकन परीक्षण",
  "IG5|1": "जनसंख्या: वितरण, घनत्व, वृद्धि",
  "IG5|2": "प्रवास",
  "IG5|3": "मानव विकास",
  "IG5|4": "मानव बस्तियाँ",
  "IG6|5": "भूमि संसाधन और कृषि",
  "IG6|6": "जल संसाधन",
  "IG7|7": "खनिज और ऊर्जा संसाधन",
  "IG7|8": "विनिर्माण उद्योग",
  "IG8|9": "नियोजन और सतत विकास",
  "IG8|10": "परिवहन और संचार",
  "IG8|11": "अंतर्राष्ट्रीय व्यापार",
  "IG8|12": "चयनित मुद्दों पर भौगोलिक परिप्रेक्ष्य",
  "WG1|1": "एक अनुशासन के रूप में भूगोल",
  "WG1|2": "पृथ्वी की उत्पत्ति और विकास",
  "WG1|3": "पृथ्वी का आंतरिक भाग",
  "WG2|4": "महासागरों और महाद्वीपों का वितरण (प्लेट टेक्टोनिक्स)",
  "WG2|5": "खनिज और चट्टानें",
  "WG3|6": "भू-आकृतिक प्रक्रियाएँ",
  "WG3|7": "स्थलाकृतियाँ और उनका विकास",
  "WG4|8": "वायुमंडल की संरचना और संघटन",
  "WG4|9": "सौर विकिरण, ऊष्मा संतुलन और तापमान",
  "WG5|10": "वायुमंडलीय परिसंचरण और मौसम प्रणालियाँ",
  "WG5|11": "वायुमंडल में जल",
  "WG5|+": "जी.सी. लियोंग — दाब पेटियाँ, पवनें, चक्रवात",
  "WG6|12": "विश्व जलवायु और जलवायु परिवर्तन",
  "WG6|+": "जी.सी. लियोंग — जलवायु के प्रकार (कोपेन क्षेत्र)",
  "WG7|13": "जल (महासागर)",
  "WG7|14": "महासागरीय जल की गतियाँ",
  "WG8|15": "पृथ्वी पर जीवन",
  "WG8|16": "जैव विविधता और संरक्षण",
  "WG9|1": "मानव भूगोल: प्रकृति और दायरा",
  "WG9|2": "विश्व जनसंख्या: वितरण, घनत्व और वृद्धि",
  "WG9|3": "जनसंख्या की संरचना",
  "WG9|4": "मानव विकास",
  "WG10|5": "प्राथमिक गतिविधियाँ",
  "WG10|6": "द्वितीयक गतिविधियाँ",
  "WG10|7": "तृतीयक और चतुर्थक गतिविधियाँ",
  "WG11|8": "परिवहन और संचार",
  "WG11|9": "अंतर्राष्ट्रीय व्यापार",
  "WG11|10": "मानव बस्तियाँ",
  "WG12|+": "सामरिक स्थान, जलडमरूमध्य, नहरें, सामयिक मामले वाले स्थान",
  "E1|1": "अर्थशास्त्र और अर्थव्यवस्था (अवधारणाएँ, क्षेत्र, राष्ट्रीय आय)",
  "E1|2": "विकास, प्रगति और खुशी",
  "E2|3": "भारतीय अर्थव्यवस्था का विकास",
  "E2|4": "आर्थिक नियोजन",
  "E3|5": "भारत में नियोजन (नीति आयोग सहित)",
  "E3|6": "आर्थिक सुधार (एलपीजी)",
  "E4|7": "मुद्रास्फीति और व्यावसायिक चक्र",
  "E5|8": "कृषि और खाद्य प्रबंधन",
  "E6|9": "उद्योग और अवसंरचना-लिंक्ड नीति",
  "E6|10": "सेवा क्षेत्र",
  "E7|11": "अवसंरचना (ऊर्जा, परिवहन, पीपीपी मॉडल)",
  "E8|12": "बैंकिंग और मौद्रिक प्रणाली",
  "E9|13": "भारत में प्रतिभूति बाजार",
  "E10|14": "भारत में बाह्य क्षेत्र (भुगतान संतुलन, विनिमय दर, व्यापार नीति)",
  "E11|15": "अंतर्राष्ट्रीय आर्थिक संगठन और भारत (आईएमएफ, विश्व बैंक, डब्ल्यूटीओ)",
  "E12|16": "भारत में कर संरचना (जीएसटी सहित)",
  "E12|17": "भारत में लोक वित्त (बजट, घाटे, एफआरबीएम)",
  "E13|18": "स्थिरता और जलवायु परिवर्तन: भारत और विश्व",
  "E13|19": "भारत में मानव विकास",
  "E14|20": "ज्वलंत सामाजिक-आर्थिक मुद्दे",
  "E14|21": "आर्थिक अवधारणाएँ और शब्दावली (शब्दावली समीक्षा)",
  "E14|+": "आर्थिक सर्वेक्षण — वर्ष के मुख्य अध्याय",
  "EN1|1": "पारिस्थितिकी — जीव और पर्यावरण",
  "EN1|2": "पारिस्थितिकी तंत्र के कार्य (ऊर्जा प्रवाह, चक्र)",
  "EN1|3": "स्थलीय पारिस्थितिकी तंत्र",
  "EN1|4": "जलीय पारिस्थितिकी तंत्र",
  "EN2|5": "जैव विविधता — अवधारणाएँ और मापन",
  "EN2|6": "भारतीय जैव विविधता और हॉटस्पॉट",
  "EN2|7": "पादप और जंतु विविधता (आईयूसीएन श्रेणियाँ)",
  "EN2|8": "समुद्री और तटीय जैव विविधता",
  "EN3|9": "संरक्षित क्षेत्र नेटवर्क (राष्ट्रीय उद्यान, वन्यजीव अभयारण्य, बायोस्फीयर रिजर्व, सामुदायिक रिजर्व)",
  "EN3|10": "संरक्षण प्रयास — प्रजाति कार्यक्रम (बाघ, हाथी, आदि)",
  "EN3|11": "अंतर्राष्ट्रीय संरक्षण सम्मेलन (सीबीडी, साइट्स, रामसर)",
  "EN3|12": "भारत में आर्द्रभूमियाँ और रामसर स्थल",
  "EN4|13": "जलवायु परिवर्तन विज्ञान",
  "EN4|14": "प्रभाव और भेद्यता",
  "EN4|15": "वैश्विक पहल — यूएनएफसीसीसी, क्योटो, पेरिस",
  "EN4|16": "भारत की जलवायु प्रतिबद्धताएँ और मिशन (एनएपीसी, एनडीसी)",
  "EN5|17": "वायु प्रदूषण (एनसीएपी सहित)",
  "EN5|18": "जल प्रदूषण",
  "EN5|19": "मृदा, ध्वनि, तापीय प्रदूषण",
  "EN5|20": "अपशिष्ट प्रबंधन (ठोस, ई-कचरा, प्लास्टिक नियम)",
  "EN6|21": "पर्यावरणीय विधान (EPA, वायु अधिनियम, जल अधिनियम, WPA, FCA)",
  "EN6|22": "संस्थान — CPCB, NGT, NBWL, आदि।",
  "EN6|23": "पर्यावरणीय प्रभाव आकलन",
  "EN6|24": "वन अधिकार और वन शासन (FRA, CAMPA)",
  "EN7|25": "सतत कृषि और जैविक खेती",
  "EN7|26": "नवीकरणीय ऊर्जा और ऊर्जा पर्यावरण",
  "EN7|27": "सतत विकास और हरित अर्थव्यवस्था",
  "EN8|28": "आपदाएं जिनका पर्यावरणीय आयाम हो",
  "EN8|29": "भू-पर्यावरणीय मुद्दे समाचारों में",
  "EN8|30": "प्रजातियाँ/स्थान समाचारों में — वार्षिक संकलन",
  "IR1|1": "भारत की विदेश नीति का विकास (गुटनिरपेक्ष आंदोलन से बहु-संरेखण तक)",
  "IR1|2": "सिद्धांत, सिद्धांत और संस्थान (MEA, पंचशील, गुजराल आदि)",
  "IR2|3": "भारत-पाकिस्तान",
  "IR2|4": "भारत-अफगानिस्तान",
  "IR3|5": "भारत-चीन",
  "IR3|6": "भारत-नेपाल",
  "IR3|7": "भारत-भूटान",
  "IR4|8": "भारत-बांग्लादेश",
  "IR4|9": "भारत-श्रीलंका",
  "IR4|10": "भारत-म्यांमार",
  "IR4|11": "भारत-मालदीव",
  "IR5|12": "भारत-संयुक्त राज्य अमेरिका",
  "IR5|13": "भारत-रूस",
  "IR6|14": "भारत-जापान, ऑस्ट्रेलिया, दक्षिण कोरिया",
  "IR6|15": "आसियान और एक्ट ईस्ट",
  "IR6|16": "इंडो-पैसिफिक और QUAD",
  "IR7|17": "भारत-पश्चिम एशिया (इज़राइल, ईरान, खाड़ी)",
  "IR7|18": "भारत-अफ्रीका",
  "IR7|19": "भारत-मध्य एशिया, लैटिन अमेरिका, यूरोप/ईयू",
  "IR8|20": "संयुक्त राष्ट्र और UNSC सुधार",
  "IR8|21": "समूह — BRICS, SCO, G20, IBSA, आदि।",
  "IR8|22": "परमाणु नीति और निर्यात-नियंत्रण व्यवस्था",
  "IR8|23": "प्रवासी, सॉफ्ट पावर, अंतर्राष्ट्रीय कानून की मूल बातें",
  "IS1|1": "अवधारणाएँ: आंतरिक बनाम बाहरी सुरक्षा, जुड़ाव",
  "IS1|2": "भारत की सुरक्षा वास्तुकला (एजेंसियां, बल, समन्वय)",
  "IS2|3": "जम्मू और कश्मीर में आतंकवाद — विकास और वर्तमान चरण",
  "IS2|4": "सीमा पार आतंकवाद और राज्य प्रायोजन",
  "IS3|5": "पूर्वोत्तर — समूह-वार उग्रवाद का नक्शा",
  "IS3|6": "शांति समझौते और AFSPA बहस",
  "IS4|7": "LWE — उत्पत्ति, प्रसार, वर्तमान स्थिति",
  "IS4|8": "सरकारी प्रतिक्रिया — सुरक्षा + विकास दृष्टिकोण (SAMADHAN)",
  "IS5|9": "आतंकवाद — प्रकार, वित्तपोषण, ध्रुवीकरण",
  "IS5|10": "संगठित अपराध — आतंकवाद से संबंध, धन शोधन (PMLA, FATF)",
  "IS6|11": "साइबर सुरक्षा — खतरे, वास्तुकला (CERT-In, NCIIPC)",
  "IS6|12": "सुरक्षा में मीडिया, सोशल मीडिया और संचार नेटवर्क की भूमिका",
  "IS7|13": "सीमा प्रबंधन — भूमि सीमाएँ, तटीय सुरक्षा",
  "IS7|14": "सुरक्षा बल — CAPFs, पुलिस सुधार, निजी सुरक्षा",
  "IS8|15": "DM Act 2005, NDMA ढाँचा, NDMP",
  "IS8|16": "2nd ARC — संकट प्रबंधन (मुख्य सिफारिशें)",
  "IS8|17": "सेंडई ढाँचा; केस स्टडीज़ — चक्रवात, बाढ़, औद्योगिक",
  "S1|1": "भारतीय समाज की विशेषताएँ; विविधता में एकता",
  "S1|2": "परिवार, नातेदारी, विवाह — रूप और परिवर्तन",
  "S1|3": "क्षेत्रवाद और विविधता प्रबंधन",
  "S2|4": "जाति व्यवस्था — निरंतरता और परिवर्तन",
  "S2|5": "जनजाति — मुद्दे और नीति",
  "S2|6": "धर्म, सांप्रदायिकता, धर्मनिरपेक्षता",
  "S3|7": "जनसांख्यिकी और जनसंख्या मुद्दे",
  "S3|8": "महिलाएँ — स्थिति, पितृसत्ता, हिंसा, सशक्तिकरण",
  "S3|9": "शहरीकरण और प्रवासन — सामाजिक प्रभाव",
  "S4|10": "वैश्वीकरण — सामाजिक प्रभाव",
  "S4|11": "गरीबी और विकासात्मक मुद्दे",
  "S4|12": "सामाजिक सशक्तिकरण और सामाजिक आंदोलन",
  "G1|1": "शासन बनाम सरकार; सुशासन संकेतक",
  "G1|2": "जवाबदेही और पारदर्शिता — RTI (ARC 1st Report)",
  "G1|3": "नागरिक चार्टर और शिकायत निवारण",
  "G2|4": "2nd ARC — शासन में नैतिकता (मुख्य सिफारिशें)",
  "G2|5": "2nd ARC — नागरिक केंद्रित प्रशासन",
  "G2|6": "सामाजिक अंकेक्षण और सहभागी शासन",
  "G3|7": "2nd ARC — ई-गवर्नेंस को बढ़ावा देना; डिजिटल इंडिया स्टैक",
  "G3|8": "लोकतंत्र में सिविल सेवाओं की भूमिका; सुधार (मिशन कर्मयोगी)",
  "G3|9": "संस्थागत और नियामक निकायों का अवलोकन",
  "G4|10": "SHGs, NGOs, सहकारी समितियाँ — विकास में भूमिका",
  "G4|11": "सरकारी योजनाएँ — वास्तुकला और मूल्यांकन ढाँचा",
  "G4|12": "विधेयकों और अधिनियमों की ट्रैकिंग विधि (PRS-आधारित)",
  "SJ1|1": "SC/ST/OBC — संवैधानिक + योजना वास्तुकला",
  "SJ1|2": "अल्पसंख्यक, विकलांग, बुजुर्ग, बच्चे, ट्रांसजेंडर व्यक्ति",
  "SJ1|3": "संबंधित निकाय और आयोग",
  "SJ2|4": "स्वास्थ्य — नीति, आयुष्मान भारत, पोषण (POSHAN)",
  "SJ2|5": "शिक्षा — NEP 2020, योजनाएं, मुद्दे",
  "SJ2|6": "कौशल विकास और रोजगार कार्यक्रम",
  "SJ3|7": "गरीबी और भुखमरी — मापन और बहसें",
  "SJ3|8": "प्रमुख कल्याणकारी योजनाएं — डिजाइन और कार्यान्वयन के मुद्दे",
  "SJ3|9": "DBT, लक्ष्यीकरण बनाम सार्वभौमिकरण बहसें",
  "ET1|1": "नैतिकता का सार, निर्धारक और परिणाम",
  "ET1|2": "नैतिकता के आयाम; निजी और सार्वजनिक संबंधों में नैतिकता",
  "ET1|3": "मानवीय मूल्य — नेताओं और सुधारकों के जीवन से सीख",
  "ET2|4": "अभिवृत्ति — सामग्री, संरचना, कार्य; नैतिक और राजनीतिक अभिवृत्तियाँ",
  "ET2|5": "सिविल सेवा के लिए अभिरुचि और मूलभूत मूल्य",
  "ET2|6": "ईमानदारी, निष्पक्षता, वस्तुनिष्ठता, समर्पण, सहानुभूति, करुणा",
  "ET3|7": "भावनात्मक बुद्धिमत्ता — अवधारणाएं और अनुप्रयोग",
  "ET3|8": "नैतिक विचारक और दार्शनिक — भारत और विश्व",
  "ET4|9": "सार्वजनिक/सिविल सेवा मूल्य और लोक प्रशासन में नैतिकता",
  "ET4|10": "नैतिक दुविधाएं, अंतरात्मा, जवाबदेही के स्रोत",
  "ET4|11": "कानून, नियम, विनियम नैतिक मार्गदर्शन के स्रोत के रूप में",
  "ET5|12": "शासन में सत्यनिष्ठा — अवधारणा और दार्शनिक आधार",
  "ET5|13": "नैतिकता/आचरण संहिता, नागरिक चार्टर, कार्य संस्कृति",
  "ET5|14": "भ्रष्टाचार की चुनौतियाँ; RTI और पारदर्शिता",
  "ET6|15": "केस-स्टडी उत्तर ढाँचा (हितधारक → विकल्प → मूल्यांकन → कार्रवाई)",
  "ET6|16": "अभ्यास: मॉडल संरचनाओं के साथ 12 वर्गीकृत केस स्टडीज",
  "ST1|1": "भौतिकी मूल बातें (परीक्षा संदर्भ में) (प्रकाशिकी, तरंगें, नाभिकीय)",
  "ST1|2": "रोजमर्रा की जिंदगी में रसायन विज्ञान (सामग्री, पॉलिमर)",
  "ST1|3": "जीव विज्ञान मूल बातें (कोशिका, आनुवंशिकी, रोग, प्रतिरक्षा)",
  "ST2|4": "अंतरिक्ष — ISRO मिशन, प्रक्षेपण यान, अनुप्रयोग",
  "ST2|5": "रक्षा प्रौद्योगिकी — मिसाइलें, प्लेटफॉर्म, DRDO",
  "ST2|6": "परमाणु ऊर्जा और कार्यक्रम",
  "ST3|7": "IT, AI/ML, रोबोटिक्स",
  "ST3|8": "दूरसंचार (5G/6G), क्वांटम प्रौद्योगिकियां, ब्लॉकचेन",
  "ST3|9": "सेमीकंडक्टर और उभरती प्रौद्योगिकी नीति",
  "ST4|10": "जैव प्रौद्योगिकी — अनुप्रयोग और मुद्दे",
  "ST4|11": "स्वास्थ्य प्रौद्योगिकियां, टीके, जीन संपादन",
  "ST4|12": "IPR व्यवस्था और भारत में S&T नीति"
};

export function getChapterNameHi(englishName, moduleId, chapter) {
  const key = moduleId != null && chapter != null ? `${moduleId}|${chapter}` : null;
  if (key && CHAPTER_NAME_HI_BY_KEY[key]) return CHAPTER_NAME_HI_BY_KEY[key];
  if (englishName && CHAPTER_NAME_HI_BY_EN[englishName]) return CHAPTER_NAME_HI_BY_EN[englishName];
  return englishName || "";
}
