import { VisionEvaluationResult, getMarks, LineFeedback } from '../types/copyEvaluation';

interface DownloadParams {
  result: VisionEvaluationResult;
  fileName?: string;
  subject?: string;
  paper?: string;
  createdAt?: string;
}

const escapeHtml = (s: string) =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const listHtml = (items: string[]) =>
  items?.length
    ? `<ul>${items.map((i) => `<li>${escapeHtml(i)}</li>`).join('')}</ul>`
    : '<p>—</p>';

const lineFeedbackHtml = (items: LineFeedback[] = []) => {
  if (!items.length) return '';
  return items
    .map(
      (row, i) => `
  <div class="line-card">
    <p><strong>Line ${i + 1}</strong></p>
    <div class="box quote">${escapeHtml(row.studentLine)}</div>
    <p><strong>Research &amp; Analysis:</strong> ${escapeHtml(row.examinerAnalysis)}</p>
    <p><strong>How to improve:</strong> ${escapeHtml(row.howToImprove)}</p>
  </div>`
    )
    .join('');
};

const sectionHtml = (title: string, section: {
  studentText?: string;
  lineFeedback?: LineFeedback[];
  strengths?: string[];
  weaknesses?: string[];
  suggestions?: string[];
  analysis?: string[];
}) => {
  if (!section) return '';
  const lines = section.lineFeedback?.length
    ? `<h3>Research &amp; Analysis (line-by-line)</h3>${lineFeedbackHtml(section.lineFeedback)}`
    : section.studentText
      ? `<div class="box">${escapeHtml(section.studentText)}</div>`
      : '';
  return `
  <h2>${escapeHtml(title)}</h2>
  ${lines}
  ${section.analysis?.length ? `<p><strong>Section summary — analysis:</strong></p>${listHtml(section.analysis)}` : ''}
  <h3>Strengths</h3>${listHtml(section.strengths || [])}
  <h3>Weaknesses</h3>${listHtml(section.weaknesses || [])}
  <h3>Suggestions</h3>${listHtml(section.suggestions || [])}`;
};

export function downloadCopyEvaluationReport({
  result,
  fileName,
  subject,
  paper,
  createdAt,
}: DownloadParams) {
  const marks = getMarks(result);
  const pct = Math.round((marks / result.maxMarks) * 100);
  const title = fileName || 'UPSC Copy Evaluation';

  const bodySections = (result.body || [])
    .map((b) => sectionHtml(b.sectionTitle || 'Body', b))
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)} — Premium Evaluation Report</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 2rem auto; padding: 0 1.5rem; color: #1e293b; line-height: 1.6; }
    h1 { color: #6b21a8; border-bottom: 2px solid #c4b5fd; padding-bottom: 0.5rem; }
    h2 { color: #5b21b6; margin-top: 1.5rem; font-size: 1.1rem; }
    h3 { color: #7c3aed; font-size: 0.95rem; margin-top: 0.75rem; }
    .score { font-size: 1.5rem; font-weight: bold; color: #7c3aed; }
    .meta { color: #64748b; font-size: 0.9rem; }
    .box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; margin: 1rem 0; white-space: pre-wrap; }
    .line-card { margin: 1rem 0; padding: 1rem; border: 1px solid #e2e8f0; border-radius: 8px; }
    .quote { font-style: italic; border-left: 3px solid #c4b5fd; }
    ul { margin: 0.5rem 0; padding-left: 1.25rem; }
    .footer { margin-top: 2rem; font-size: 0.8rem; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>UPSC Mains — Premium Copy Evaluation</h1>
  <p class="meta">${escapeHtml([subject, paper, createdAt ? new Date(createdAt).toLocaleString() : ''].filter(Boolean).join(' · '))}</p>
  <p class="meta">File: ${escapeHtml(fileName || 'Answer copy')}</p>
  <p class="score">Score: ${marks} / ${result.maxMarks} (${pct}%) · Words: ~${result.wordCount || '—'} · Limit: ${result.wordLimitStatus || 'GOOD'}</p>

  ${result.questionText ? `<h2>Question</h2><div class="box">${escapeHtml(result.questionText)}</div>` : ''}
  ${result.extractedAnswerText ? `<h2>Transcribed Answer</h2><div class="box">${escapeHtml(result.extractedAnswerText)}</div>` : ''}

  ${result.questionDemand ? `
  <h2>Question Demand</h2>
  <h3>Expected Points</h3>${listHtml(result.questionDemand.expectedPoints || [])}
  <h3>Missing Areas</h3>${listHtml(result.questionDemand.missingAreas || [])}
  ` : ''}

  ${result.introduction ? sectionHtml('Introduction', result.introduction) : ''}
  ${bodySections}
  ${result.conclusion ? sectionHtml('Conclusion', result.conclusion) : ''}

  <h2>Overall Feedback</h2><p>${escapeHtml(result.overallFeedback || result.summary || '')}</p>

  <h2>Improvement Priority</h2>${listHtml(result.improvementPriority || result.suggestions || [])}
  <h2>Model Answer Framework</h2>${listHtml(result.modelAnswerSuggestions || [])}

  <h2>Examiner Remark</h2><div class="box">${escapeHtml(result.examinerRemark || result.examinerFeedback || '')}</div>

  <p class="footer">Generated by Mentors Daily — Premium Copy Evaluation</p>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(fileName || 'evaluation').replace(/\.[^.]+$/, '')}-report.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
