import { VisionEvaluationResult } from '../components/copy-evaluation/CopyEvaluationResultView';

interface DownloadParams {
  result: VisionEvaluationResult;
  fileName?: string;
  subject?: string;
  paper?: string;
  createdAt?: string;
}

const escapeHtml = (s: string) =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const listHtml = (items: string[]) =>
  items?.length
    ? `<ul>${items.map((i) => `<li>${escapeHtml(i)}</li>`).join('')}</ul>`
    : '<p>—</p>';

export function downloadCopyEvaluationReport({
  result,
  fileName,
  subject,
  paper,
  createdAt,
}: DownloadParams) {
  const pct = Math.round((result.overallMarks / result.maxMarks) * 100);
  const title = fileName || 'UPSC Copy Evaluation';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)} — Evaluation Report</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 2rem auto; padding: 0 1.5rem; color: #1e293b; line-height: 1.6; }
    h1 { color: #6b21a8; border-bottom: 2px solid #c4b5fd; padding-bottom: 0.5rem; }
    h2 { color: #5b21b6; margin-top: 1.5rem; font-size: 1.1rem; }
    .score { font-size: 1.5rem; font-weight: bold; color: #7c3aed; }
    .meta { color: #64748b; font-size: 0.9rem; }
    .box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem; margin: 1rem 0; white-space: pre-wrap; }
    ul { margin: 0.5rem 0; padding-left: 1.25rem; }
    .footer { margin-top: 2rem; font-size: 0.8rem; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>UPSC Mains — Copy Evaluation Report</h1>
  <p class="meta">${escapeHtml([subject, paper, createdAt ? new Date(createdAt).toLocaleString() : ''].filter(Boolean).join(' · '))}</p>
  <p class="meta">File: ${escapeHtml(fileName || 'Answer copy')}</p>
  <p class="score">Score: ${result.overallMarks} / ${result.maxMarks} (${pct}%)</p>

  ${result.questionText ? `<h2>Question</h2><div class="box">${escapeHtml(result.questionText)}</div>` : ''}

  ${result.extractedAnswerText ? `<h2>Your Answer (Transcribed)</h2><div class="box">${escapeHtml(result.extractedAnswerText)}</div>` : ''}

  <h2>Summary</h2><p>${escapeHtml(result.summary)}</p>

  <h2>Strengths</h2>${listHtml(result.strengths)}
  <h2>Weaknesses</h2>${listHtml(result.weaknesses)}
  ${result.missingDimensions?.length ? `<h2>Missing Dimensions</h2>${listHtml(result.missingDimensions)}` : ''}

  <h2>Content Feedback</h2><p>${escapeHtml(result.contentFeedback)}</p>
  <h2>Presentation Feedback</h2><p>${escapeHtml(result.presentationFeedback)}</p>
  <h2>Suggestions</h2>${listHtml(result.suggestions)}

  ${result.improvedConclusion ? `<h2>Model Conclusion</h2><div class="box">${escapeHtml(result.improvedConclusion)}</div>` : ''}

  <h2>Examiner Feedback</h2><div class="box">${escapeHtml(result.examinerFeedback)}</div>

  <p class="footer">Generated by Mentors Daily — Copy Evaluation</p>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(fileName || 'evaluation').replace(/\.[^.]+$/, '')}-report.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
